"""esquema inicial v2: catalogos, lotes, cohortes, eventos, users

Revision ID: a7b4f54ee359
Revises: 
Create Date: 2026-07-26 12:02:13.019914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b4f54ee359'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_frasco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('capacidad', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_medio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'operador', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('especies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('morfologia', sa.String(length=255), nullable=True),
    sa.Column('numero_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especie_id', sa.Integer(), nullable=False),
    sa.Column('tipo_frasco_id', sa.Integer(), nullable=False),
    sa.Column('tipo_medio_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_sembrada', sa.Integer(), nullable=False),
    sa.Column('fecha_siembra', sa.Date(), nullable=False),
    sa.Column('folio', sa.String(length=60), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id'], ),
    sa.ForeignKeyConstraint(['tipo_frasco_id'], ['tipos_frasco.id'], ),
    sa.ForeignKeyConstraint(['tipo_medio_id'], ['tipos_medio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('cohortes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('parent_cohorte_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=60), nullable=True),
    sa.Column('fase', sa.Enum('inicio', 'multiplicacion', 'enraizamiento', 'endurecimiento', 'rescate_1', 'rescate_2', 'normal', 'contaminado', 'descartado', name='fasecohorte'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_ultima_revision', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['parent_cohorte_id'], ['cohortes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_cohortes_lote_id'), 'cohortes', ['lote_id'], unique=False)
    op.create_index(op.f('ix_cohortes_parent_cohorte_id'), 'cohortes', ['parent_cohorte_id'], unique=False)
    op.create_table('eventos_cohorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohorte_padre_id', sa.Integer(), nullable=False),
    sa.Column('cohorte_hija_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.Enum('sin_cambios', 'multiplicacion', 'contaminacion', 'endofitos', 'rescate_exito', 'rescate_persiste', 'rescate_falla', 'enraizamiento', 'endurecimiento', name='tipoevento'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cohorte_hija_id'], ['cohortes.id'], ),
    sa.ForeignKeyConstraint(['cohorte_padre_id'], ['cohortes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_cohorte_cohorte_hija_id'), 'eventos_cohorte', ['cohorte_hija_id'], unique=False)
    op.create_index(op.f('ix_eventos_cohorte_cohorte_padre_id'), 'eventos_cohorte', ['cohorte_padre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_cohorte_cohorte_padre_id'), table_name='eventos_cohorte')
    op.drop_index(op.f('ix_eventos_cohorte_cohorte_hija_id'), table_name='eventos_cohorte')
    op.drop_table('eventos_cohorte')
    op.drop_index(op.f('ix_cohortes_parent_cohorte_id'), table_name='cohortes')
    op.drop_index(op.f('ix_cohortes_lote_id'), table_name='cohortes')
    op.drop_table('cohortes')
    op.drop_table('lotes')
    op.drop_table('especies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tipos_medio')
    op.drop_table('tipos_frasco')
    op.drop_table('generos')
    # ### end Alembic commands ###
